python/2018 - 2020/mcpgo/src/api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('login/', ObtainAuthToken.as_view(), name = 'login'),
    path('getall/', McpmasterlistAPI.as_view(), name = 'getall'),
    path('mcpdata/', McpDataAPI.as_view(), name = 'mcpdata'),
    path('createuser/', RegisterUserAPI.as_view(), name = 'createuser'),
]

python/2018 - 2020/mcpgo/src/apps/urls.py
from django.urls import path


from .views import *

app_name = 'apps'


urlpatterns = [
    # BACKEND FUNCTION
    path('approve/account/<int:pk>/', approve_account, name = 'approve'),

    # AUTHENTICATION VIEW
    path('', AuthenticateLoginView.as_view(), name = 'login'),
    path('logout/', AuthenticateLogoutView.as_view(), name = 'logout'),

    # TEMPLATE VIEW
    path('dashboard/', dashboard, name = 'dashboard'),

    # CREATE VIEW
    path('syncfile/', SyncFileFormView.as_view(), name = 'syncfile'),
    path('newaccount/', AccountCreateView.as_view(), name = 'newaccount'),


    # DELETE VIEW
    path('deleteaccount/<int:pk>/', AccountDeleteView.as_view(), name = 'deleteaccount'),

    # LIST VIEW
    path('accountlist/', AccountListView.as_view(), name = 'accountlist'),
    path('gtmlist/', GtmListView.as_view(), name = 'gtmlist'),
    path('saleslist/<path:gtm>/', SalesListView.as_view(), name = 'saleslist'),
    path('customerlist/<path:salesperson>/', CustomerListView.as_view(), name = 'customerlist'),
    path('datalist/', AssignedGtmListView.as_view(), name = 'datalist'),

    # DETAIL VIEW
    path('customerinfo/<int:pk>/', CustomerInfoDetailView.as_view(), name = 'customerinfo'),
]

python/2018 - 2020/mcpgo/src/src/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   path('', include('apps.urls', namespace = 'apps')),
   path('api/', include('api.urls', namespace = 'api')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)

python/2018 - 2020/mcpgo/src/templates/components/dashboard.html
{% extends 'base/panel.html' %}

{% block content %}
<div class="panel panel-container">
    <div class="row">
        {% if request.user.groups.all.first|lower == 'admin' %}
        <a href="{% url 'apps:accountlist' %}">
            <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
                <div class="panel panel-teal panel-widget border-right">
                    <div class="row no-padding"><em class="fa fa-xl fa-users color-blue"></em>
                        <div class="medium">ACCOUNTS</div>
                    </div>
                </div>
            </div>
        </a>
        <a href="{% url 'apps:gtmlist' %}">
            <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
                <div class="panel panel-blue panel-widget border-right">
                    <div class="row no-padding"><em class="fa fa-xl fa-table color-orange"></em>
                        <div class="medium">MCP</div>
                    </div>
                </div>
            </div>
        </a>
        {% endif %}
    </div><!--/.row-->
</div>
{% endblock %}