python/2018 - 2020/mcpgo/src/api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('login/', ObtainAuthToken.as_view(), name = 'login'),
    path('getall/', McpmasterlistAPI.as_view(), name = 'getall'),
    path('mcpdata/', McpDataAPI.as_view(), name = 'mcpdata'),
    path('createuser/', RegisterUserAPI.as_view(), name = 'createuser'),
]

python/2018 - 2020/mcpgo/src/apps/urls.py
from django.urls import path


from .views import *

app_name = 'apps'


urlpatterns = [
    # BACKEND FUNCTION
    path('approve/account/<int:pk>/', approve_account, name = 'approve'),

    # AUTHENTICATION VIEW
    path('', AuthenticateLoginView.as_view(), name = 'login'),
    path('logout/', AuthenticateLogoutView.as_view(), name = 'logout'),

    # TEMPLATE VIEW
    path('dashboard/', dashboard, name = 'dashboard'),

    # CREATE VIEW
    path('syncfile/', SyncFileFormView.as_view(), name = 'syncfile'),
    path('newaccount/', AccountCreateView.as_view(), name = 'newaccount'),


    # DELETE VIEW
    path('deleteaccount/<int:pk>/', AccountDeleteView.as_view(), name = 'deleteaccount'),

    # LIST VIEW
    path('accountlist/', AccountListView.as_view(), name = 'accountlist'),
    path('gtmlist/', GtmListView.as_view(), name = 'gtmlist'),
    path('saleslist/<path:gtm>/', SalesListView.as_view(), name = 'saleslist'),
    path('customerlist/<path:salesperson>/', CustomerListView.as_view(), name = 'customerlist'),
    path('datalist/', AssignedGtmListView.as_view(), name = 'datalist'),

    # DETAIL VIEW
    path('customerinfo/<int:pk>/', CustomerInfoDetailView.as_view(), name = 'customerinfo'),
]

python/2018 - 2020/mcpgo/src/src/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   path('', include('apps.urls', namespace = 'apps')),
   path('api/', include('api.urls', namespace = 'api')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)

python/2018 - 2020/mcpgo/src/templates/components/crud/detail.html
{% extends 'base/panel.html' %}

{% block content %}
<table class="table table-responsive">
    <tr>
        <td style="width: 100%; background-color:#000000; color: #ffffff;" colspan="3">Customer Name:</td>
    </tr>
    <tr>
        <td colspan="3">{{ object.customer|upper }}</td>
    </tr>
    <tr>
        <td style="width: 100%; background-color:#000000; color: #ffffff;" colspan="3">Address:</td>
    </tr>
    <tr>
        <td colspan="3">{{ object.address|upper }}</td>
    </tr>
    <tr>
        <td style="width: 50%; background-color:#000000; color: #ffffff;">GTM:</td>
        <td style="width: 50%; background-color:#000000; color: #ffffff;" colspan="2">Salesperson:</td>
    </tr>
    <tr>
        <td>{{ object.gtm|upper }}</td>
        <td colspan="2">{{ object.salesperson|upper }}</td>
    </tr>
    <tr>
        <td style="width: 30%; background-color:#000000; color: #ffffff;">Channel:</td>
        <td style="width: 30%; background-color:#000000; color: #ffffff;">Freq:</td>
        <td style="width: 30%; background-color:#000000; color: #ffffff;">Odd / Even:</td>
    </tr>
    <tr>
        <td>{{ object.channel }}</td>
        <td>{{ object.freq }}</td>
        <td>{{ object.odd_even }}</td>
    </tr>
    <tr>
        <td style="width: 30%; background-color:#000000; color: #ffffff;">AVE NPS.:</td>
        <td style="width: 30%; background-color:#000000; color: #ffffff;">C-TERM:</td>
        <td style="width: 30%; background-color:#000000; color: #ffffff;">C-LIMIT:</td>
    </tr>
    <tr>
        <td>{{ object.ave_nps }}</td>
        <td>{{ object.cterm }}</td>
        <td>{{ object.climit }}</td>
    </tr>
</table>
{% endblock %}

python/2018 - 2020/mcpgo/src/templates/components/crud/form.html
{% extends 'base/panel.html' %}

{% load static %}

{% block content %}

{% include 'helpers/message.html' %}

<form action="" method="post" {{ context_enctype|safe }}>
    {% csrf_token %}
    {% include 'helpers/form.html' %}
    <div class="form-group">
        <button type="submit" class="btn btn-md btn-primary form-control" data-backdrop="static" data-toggle="modal" data-target="#load">{{ context_button_title }}</button>
    </div>
</form>

<!-- Modal -->
<div class="modal fade" id="load" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-body">
        <img src="{% static 'loading.gif' %}" alt="LOADING" style="width: 100px; height: 100px;" /> Please wait . . .
    </div>
    </div>
</div>
</div>
{% endblock %}

python/2018 - 2020/mcpgo/src/templates/components/crud/read.html
{% extends 'base/panel.html' %}

{% load static %}

{% block link_stylesheet %}
<link rel="stylesheet" href="{% static 'DataTables/datatables.css' %}">
{% endblock %}

{% block script %}
<script src="{% static 'DataTables/datatables.js' %}"></script>
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    });

    function removeQuery(val) {
        document.querySelector('form[data-load-modal-form]').action = val;
    }
</script>
{% endblock %}

{% block content %}

{% include 'helpers/message.html' %}

{{ context_links|safe }}

<table id="table_id" class="table table-responsive display">
    <thead>
        {% if context_title|lower == 'gtm list' %}
        <tr>
            <th>GTM</th>
            <th></th>
        </tr>
        {% elif context_title|lower == 'salesperson list' %}
        <tr>
            <th>SALESPERSON</th>
            <th></th>
        </tr>
        {% elif context_title|lower == 'customer list' %}
        <tr>
            <th>CUSTOMER</th>
            <th></th>
        </tr>
        {% elif context_title|lower == 'account list' %}
        <tr>
            <th>FULLNAME</th>
            <th>USERNAME</th>
            <th>EMAIL</th>
            <th>USER TYPE</th>
            <th>ACCOUNT STATUS</th>
            <th></th>
        </tr>
        {% endif %}
    </thead>
    <tbody>
        {% if context_title|lower == 'gtm list' %}
            {% for field in object %}
            <tr>
                <td>{{ field.gtm|upper }}</td>
                <td>
                    <a href="{% url 'apps:saleslist' gtm=field.gtm %}" class="btn btn-sm btn-default">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        {% elif context_title|lower == 'salesperson list' %}
            {% for field in object %}
            <tr>
                <td>{{ field.salesperson|upper }}</td>
                <td>
                    <a href="{% url 'apps:customerlist' salesperson=field.salesperson %}" class="btn btn-sm btn-default">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        {% elif context_title|lower == 'customer list' %}
            {% for field in object %}
            <tr>
                <td>{{ field.customer|upper }}</td>
                <td>
                    <a href="{% url 'apps:customerinfo' pk=field.pk %}" class="btn btn-sm btn-default">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                    <a href="" class="btn btn-sm btn-primary">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="" class="btn btn-sm btn-danger">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        {% elif context_title|lower == 'account list' %}
            {% for field in object %}
            <tr>
                <td>{% if field.first_name != '' %}{{ field.first_name|upper }}, {{ field.last_name|upper }}{% else %}Not Available{% endif %}</td>
                <td><i>@{{ field.username }}</i></td>
                <td>{{ field.email }}</td>
                <td>{% if field.user_type == '2' %}GTM{% elif field.user_type == '3' %}SALES{% elif field.user_type == '1' %}ADMIN{% endif %}</td>
                <td>{{ field.account_status|upper }}</td>
                <td>
                    <a href="" class="btn btn-sm btn-default">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                    {% if field.account_status == 'pending' %}
                        <a href="{% url 'apps:approve' pk=field.pk %}" class="btn btn-sm btn-success">
                            <i class="fa fa-check"></i>
                        </a>
                    {% endif %}
                    <a href="" class="btn btn-sm btn-primary">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#modalForm" onclick="removeQuery('{% url 'apps:deleteaccount' pk=field.pk %}')">
                        <i class="fa fa-trash"></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
        {% endif %}

    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure to remove this?
        </div>
        <div class="modal-footer">
          <form action="" method="post" data-load-modal-form>
            {% csrf_token %}
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Yes</button>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}